env:
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  import/extensions: [error, { "js": "ignorePackages" }],
  no-console: 'off',
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }],
}
